### ISSUE TITLE
Errors copying reference files after the "ember backstop reference" command

### ISSUE THREAD

**Issue by sglanzer** [johnjmartin/ember-cli-backstop#2]
Starting backstop reference ..

gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn casperjs ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

Error thrown while generating reference files
Error: Command failed: /bin/sh -c ../gulp/bin/gulp.js reference
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn casperjs ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
Error thrown while trying to move bitmaps to tests/backstop 
Error: ENOENT, lstat '/home/sglanzer/Documents/Projects/backstop-test/node_modules/ember-cli-backstop/node_modules/backstopjs/bitmaps_reference'
    at Error (native)

**Comment by johnjmartin** [comment]
Is this the bug you had earlier today?

**Comment by sglanzer** [comment]
Yes, confirmed again on another system.  I believe your test system may have some environment settings that are avoiding this issue.  We should find another system to test this defect against.

**Comment by johnjmartin** [comment]
Alright, I will come by tomorrow morning and we can try it on Kevin's machine.

**Comment by sglanzer** [comment]
Still issues with the casperjs dependency.  I'd recommend documenting the installation of casperjs as an npm global install for now and exploring options to encapsulate this dependency later.

**Comment by sglanzer** [comment]
Hmm, may not be an issue with the blueprint - looks like my global dependencies are screwed up a bit

**Comment by sglanzer** [comment]
Fixed my global npm location and it works.  I had to install phantomjs as well.  I think it makes sense to list these dependencies in the same way ember-cli does:

http://www.ember-cli.com/user-guide/#phantomjs

That way we can avoid hitting people's specific npm issues.  Let me know what you think.

**Comment by johnjmartin** [comment]
Sure that makes sense. I thought we were assuming that phantomjs would be installed but you're right, we should specify for both.

**Comment by sglanzer** [comment]
We were, but I stumbled across the case when it isn't installed and Casper
complains, so it's better to make it explicit

**Comment by sglanzer** [comment]
Resolved via documentation
