### ISSUE TITLE
Move vs. copy during backstop commands

### ISSUE THREAD

**Issue by sglanzer** [johnjmartin/ember-cli-backstop#6]
- [x] The tests command should copy the backstop.json from tests/backstop.json into the execution directory
- [x] I don't understand why we would move (or copy + remove) the reference files during the tests command, we should just copy those files into the target/test execution directory and leave the source files alone - at most we might want to clear the target/test execution directory after the test finishes
- [ ] The reference command shouldn't delete the reference files, but rather force overwrite and remove any files that are no longer part of the reference.  We don't want to get stuck in a case where a command fails we we've deleted all the reference files...
- [x] Take a look at the command sequences to see if we can remove some of the steps (we should be able to if we're doing copy instead of move for some of these cases)

**Comment by johnjmartin** [comment]
1. I believe the tests command does copy the backtop.json to the execution directory.
2. I only did that to be cleaner in the execution of the tests but you're right, it really isn't serving any purpose.
3. Not sure how to remove the files that are no longer a part of the reference but we can move that command to the very end so if an error occurs we don't delete the reference files

**Comment by sglanzer** [comment]
1. Line 30 of the commands/backstop.js is using 

```
function moveBackstopJSONFromTests() {
  return new RSVP.Promise(function (resolve, reject) {
    fs.move(projectJSONPath, backstopJSONPath, function (error) {
```

**Comment by sglanzer** [comment]
3. We can work on that - definitely want to make sure we don't mess with the committed reference files

**Comment by sglanzer** [comment]
Questionable whether or not the removal of stale references is a tool or user operation.  We're taking the approach of tool currently, but may change this opinion in the future.
