### ISSUE TITLE
ember backstop reference generates blank image for root

### ISSUE THREAD

**Issue by FanaHOVA** [johnjmartin/ember-cli-backstop#8]
Hey there. Trying to implement this in my app but all the generated screenshots are blank for some reason; my backstop.json:

```
{
  "viewports": [
    {
      "name": "desktop",
      "width": 1920,
      "height": 1080
    }
  ],
  "scenarios": [
    {
      "label": "Landing",
      "url": "http://localhost:4200/",
      "hideSelectors": [],
      "selectors": [
        "body"
      ],
      "readyEvent": "tweet loaded",
      "delay": 2000,
      "misMatchThreshold" : 0.1
    }
  ]
}
```

I've already tried without readyEvent and a longer delay as well with no luck. The issue is that casperjs times out for some reason; any way to work around this? It gets stuck on `Starting backstop reference ..` and doesn't progress. The tab is open on my browser when I launch the command; it works fine with other routes though, so it's really weird.

**Comment by FanaHOVA** [comment]
Solved by running the server with `--environment=production`

**Comment by garris** [comment]
:+1:  for adding the resolution!
